export const filters = [
  {
    user_id: "1",
    smartFilter: true,
    dishType: "sju",
    cuisine: "haha",
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    readyInMinutes: 77,
    servings: 77,
  },
  {
    user_id: "2",
    smartFilter: false,
    dishType: "kameler",
    cuisine: "hoho",
    vegetarian: false,
    vegan: true,
    glutenFree: true,
    dairyFree: false,
    readyInMinutes: 7,
    servings: 7,
  },
  {
    user_id: "3",
    smartFilter: true,
    dishType: "hundar",
    cuisine: "hehe",
    vegetarian: false,
    vegan: true,
    glutenFree: true,
    dairyFree: false,
    readyInMinutes: 777,
    servings: 777,
  },
];
